### ISSUE TITLE
Duplicate awesome list

### ISSUE THREAD

**Issue by whoabuddy** [crypt0biwan/awesome-ordinals#2]
Flagging that there are now two Ordinal awesome lists, I found this one through Twitter and think the layout is very clean. It'd be good to either get them in sync or merge them a I see some differences between the two. https://github.com/neu-fi/awesome-ordinals/issues/6

Also you can see the original discussion about the awesome list [here in the ord repo](https://github.com/casey/ord/issues/1480), having one canonical resource would likely be best.

~~*Note: see the [formatting update here](https://github.com/whoabuddy/awesome-ordinals/tree/fix/add-more-resources) for what I'm proposing in an open PR*~~

**Comment by crypt0biwan** [comment]
Thanks for pointing this out, I think it's good that we both maintain our lists, some nice competition ;-)
And of course people are free to use what they prefer
